### PR TITLE
created the basic sign up page

### PR DESCRIPTION
**Pull request by johnjang94**
the logic:
- the user will be able to direct themselves to the sign up page using the link at the bottom of the login page
- the user needs to fill out name, email, and password in the form.
- the user then needs to click to agree terms and conditions (or the sign up button will not be activated)
- once the user has successfully filled out everything, the user will automatically be redirected to the login page after 3 seconds.

created the following screens:
Screenshot 2024-08-16 at 1 15 59 PM
Screenshot 2024-08-16 at 1 15 02 PM
Screenshot 2024-08-16 at 1 15 24 PM
Screenshot 2024-08-16 at 1 15 49 PM
Screenshot 2024-08-16 at 1 15 59 PM

### CODE REVIEW

**Comment by Gaurav-Narayan-Varma** [comment]
Bug: Clicking the sign up button does not redirect me to the desired screen, see snippet below:

https://github.com/user-attachments/assets/eb4642c0-d878-4a0a-bbb5-403eb38b78e6

**Comment by johnjang94** [comment]
made the following changes:

https://github.com/user-attachments/assets/b80d3d32-d107-4663-9b0e-0783db392dbd

**Comment by Gaurav-Narayan-Varma** [comment]
Could you refactor this form using React Hook Forms? A few advantages over the current approach:

1. Simplified state management: React Hook Form can significantly reduce the amount of state you need to manage. Currently, you have multiple state variables for each input field and their validation states. React Hook Form handles this internally, reducing boilerplate code.
2. Performance optimization: React Hook Form is designed to minimize re-renders, which can improve the overall performance of your form, especially for larger forms.
3. Built-in validation: While you've implemented custom validation logic, React Hook Form provides built-in validation that can simplify your code. It supports both synchronous and asynchronous validation out of the box.
4. Easier form submission: React Hook Form simplifies the form submission process by gathering all form data automatically, reducing the need for manual data collection.
5. Error handling: It provides a more streamlined way to handle and display error messages, which could simplify your current error state management.
7. TypeScript support: If you're using TypeScript (which it appears you are), React Hook Form has excellent TypeScript support, providing better type safety for your form data

Also I think the team is already using RHF since we agreed to use it:
Screenshot 2024-08-16 202334

**Comment by johnjang94** [comment]
That's actually true!
Before my previous PR, I did implement react hook form. Then I was applying another dependency along with the react hook form which messed up the code (and I was getting tired). I just deleted everything and manually request PR with the previous code, but I should have been sticking to my gut to stay with react hook form at least.

For my most recent PR, I did implement react hook form again.
For more changes, I also noticed that we apparently need a phone number instead of password???
Screenshot 2024-08-18 at 10 10 31 AM

...so instead of keeping the password input, I have replaced the inputs with the input for the phone number.
Here is the video of the changes applied:

https://github.com/user-attachments/assets/8b4d2b15-ebd6-446d-8039-461a85f8696f

**Comment by Gaurav-Narayan-Varma** [comment]
@johnjang94 Great work on this implementation! Your quick turnaround and incorporation of Michelle's feedback on the form requirements are much appreciated. I'd like to suggest a few optimizations that can enhance the performance and simplify the code:

1. Optimizing re-renders: Currently, the use of watch is causing re-renders on every keystroke, which can impact performance. React Hook Form (RHF) offers more efficient ways to track input fields without triggering unnecessary re-renders. Instead of watch, we can leverage formState.errors to validate inputs in real-time. To achieve this, set useForm's mode and reValidateMode to "onChange". This approach maintains responsiveness without the performance overhead.
2. Tracking touched fields: Rather than managing separate state for touched fields, we can utilize RHF's built-in formState.touchedFields. This simplifies our code and reduces state management overhead.
3. Form validity tracking: The custom isFormValid logic can be replaced with RHF's formState.isValid. This built-in feature automatically tracks overall form validity, allowing us to control the submit button's disabled state more efficiently.

Here's a video demonstrating the current re-render behavior:
https://github.com/user-attachments/assets/ac3b762e-0af4-483d-af6e-8fbf4a8c32ce

By implementing these suggestions, we can significantly reduce unnecessary re-renders and streamline our form handling. Let me know if you'd like any assistance in refactoring the code to incorporate these optimizations!

**Comment by johnjang94** [comment]
I think that I've corrected it now :) Thanks for checking thorougly.

https://github.com/user-attachments/assets/cfc0866a-c21f-4332-93c0-5235fe3eb6c9

**Pull request merged**
