### PR TITLE
Finished Home page UI

### PR DESCRIPTION
**Pull request by fuguoxue-nyu**

### CODE REVIEW

**Comment by fuguoxue-nyu** [comment]
Hi John, thank you for the reminder! I just resolved the conflict, please have a look :)

**Comment by fuguoxue-nyu** [comment]
> Would you like me to resolve the conflict, Fuguo?

Hi John, thank you for the reminder! I just resolved the conflict, please have a look :)

**Comment by johnjang94** [comment]
Thank you for resolving the conflict, Fuguo. 
It looks like you are having some CSS issues on my end. Would you mind to look into the CSS again, please?

Screenshot 2024-08-29 at 10 33 57 AM

**Comment by johnjang94** [comment]
I am dropping my suggestion to you. Here is the example of how I would adjust the code:

=> home > page.tsx
```import ListItems from "../../data/list-items.json";
import Image from "next/image";
import Thumbnail from "./list-thumbnail.png";
import { GoTriangleRight } from "react-icons/go";
import "./clock-in";
import ClockIn from "./clock-in";

export default function Home() {
  const date = new Date();
  const day = date.getDate();
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  const month = months[date.getMonth()];
  const year = date.getFullYear();
  const currentDate = month + " " + day + ", " + year;
  return (
    <div className="w-full">
      <header className="space-y-1 mt-20 mb-4">
        <p className="text-xs text-center">
          We appreciate everything you do to keep our community safe.
        </p>
        <p className="text-[10px] text-center">{currentDate}</p>
      </header>

      <ClockIn />

      <section>
        <div className="flex text-sm my-3">
          <h1 className="font-bold">Pinned Announcements</h1>
          <a href="#" className="underline text-link ml-auto">
            See all
          </a>
        </div>
        {ListItems.map((listItem, index) => (
          <div key={index} className="mb-2 py-2 px-4 bg-homelistbg flex">
            <Image
              src={Thumbnail}
              width={56}
              height={56}
              alt="List item thumbnail"
              className="self-center"
            />
            <div className="pl-4 self-center w-52">
              <h6 className="text-sm">{listItem.title}</h6>
              <p className="text-xs">{listItem.detail}</p>
            </div>
            <GoTriangleRight className="ml-auto self-center text-lg text-primary" />
          </div>
        ))}
      </section>
    </div>
  );
}
```
Preview:
Screenshot 2024-08-29 at 10 58 11 AM


=> home > clock-in.js
```"use client";
import { useState } from "react";
import { LuClock } from "react-icons/lu";

export default function ClockIn() {
  const [clockIn, setClockIn] = useState(false);

  return (
    <div>
      {clockIn ? (
        <div className="space-y-1">
          <p className="text-xs text-center">Click here to end your shift</p>
          <button
            className="bg-white py-3 mb-2 w-full rounded-3xl text-sm font-medium text-primary border-default border-2 text-center align-middle inline-flex justify-center drop-shadow-lg"
            type="button"
            onClick={() => setClockIn(!clockIn)}
          >
            <LuClock className="self-center mr-2 text-base" />
            <span className="ml-2">Clock Out</span>
          </button>
          <p className="text-xs text-center my-1">
            2 hours til your shift ends!
          </p>
        </div>
      ) : (
        <div>
          <p className="text-xs text-center mb-2">
            Click here to start your shift
          </p>
          <button
            className="bg-primary py-3 mb-2 w-full rounded-3xl text-sm font-medium text-white text-center align-middle inline-flex justify-center drop-shadow-lg"
            type="button"
            onClick={() => setClockIn(!clockIn)}
          >
            <LuClock className="self-center mr-2 text-base" />
            <span className="ml-2">Clock In</span>
          </button>
        </div>
      )}
    </div>
  );
}
```
Preview:
Screenshot 2024-08-29 at 10 58 20 AM

**Comment by fuguoxue-nyu** [comment]
Hi John, thank you! I see why the page looks differently: somehow my local home branch is not synchronized to the remote home branch, which caused the difference in page width.

**Comment by johnjang94** [comment]
Thank you for taking my suggestion into account! I will go ahead and merge your changes!

**Pull request merged**
